# Generated by Django 2.0.4 on 2018-05-02 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=32)),
                ('country_code', models.CharField(max_length=2)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='mobapp.Event')),
            ],
        ),
    ]
