# Generated by Django 2.0.5 on 2018-05-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobapp', '0002_ownednumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('msisdn', models.CharField(db_index=True, max_length=32)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='mobapp.Event')),
            ],
        ),
        migrations.AlterField(
            model_name='ownednumber',
            name='msisdn',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'msisdn')},
        ),
    ]
